import { useState } from 'react';
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { VitalButton } from '@/components/vitalpilot/button';
import { VitalCard } from '@/components/vitalpilot/card';
import { BottomTabInset } from '@/constants/theme';
import { VitalPilotColors } from '@/constants/vitalpilot';

const periods = [
  '7 Days',
  '30 Days',
  '90 Days',
];

export default function ReportsScreen() {
  const [period, setPeriod] = useState('30 Days');
  const [reportGenerated, setReportGenerated] = useState(false);
  const [message, setMessage] = useState('');

  function generateReportPreview() {
    setReportGenerated(true);
    setMessage(
      `Report preview generated for the last ${period}.`
    );
  }

  function downloadPdf() {
    if (!reportGenerated) {
      setMessage(
        'Generate the report preview before downloading the PDF.'
      );
      return;
    }

    setMessage(
      'PDF download will be connected when the reporting backend is available.'
    );
  }

  function selectPeriod(selectedPeriod: string) {
    setPeriod(selectedPeriod);
    setReportGenerated(false);
    setMessage('');
  }

  return (
    <SafeAreaView
      style={styles.safeArea}
      edges={['top']}
    >
      <ScrollView
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.title}>
          Health Reports
        </Text>

        <Text style={styles.subtitle}>
          Review trends and prepare a summary to share
          with a healthcare provider.
        </Text>

        <View style={styles.periodRow}>
          {periods.map((item) => {
            const isSelected = period === item;

            return (
              <Pressable
                key={item}
                onPress={() => selectPeriod(item)}
                style={({ pressed }) => [
                  styles.period,
                  isSelected &&
                    styles.periodSelected,
                  pressed && styles.pressed,
                ]}
              >
                <Text
                  style={[
                    styles.periodText,
                    isSelected &&
                      styles.periodTextSelected,
                  ]}
                >
                  {item}
                </Text>
              </Pressable>
            );
          })}
        </View>

        <VitalCard>
          <Text style={styles.cardTitle}>
            Trend Overview
          </Text>

          <View style={styles.metricRow}>
            <Text style={styles.metricLabel}>
              Blood Pressure
            </Text>

            <Text style={styles.metricValue}>
              128/82 mmHg
            </Text>
          </View>

          <View style={styles.metricRow}>
            <Text style={styles.metricLabel}>
              Blood Glucose
            </Text>

            <Text style={styles.metricValue}>
              102 mg/dL
            </Text>
          </View>

          <View style={styles.metricRow}>
            <Text style={styles.metricLabel}>
              Blood Oxygen
            </Text>

            <Text style={styles.metricValue}>
              98%
            </Text>
          </View>

          <View style={styles.metricRow}>
            <Text style={styles.metricLabel}>
              Sleep
            </Text>

            <Text style={styles.metricValue}>
              7.4 hours
            </Text>
          </View>
        </VitalCard>

        <VitalCard>
          <Text style={styles.cardTitle}>
            Clinical Progress Summary
          </Text>

          {reportGenerated ? (
            <Text style={styles.body}>
              During the selected {period.toLowerCase()} period,
              your recorded health measurements remained
              generally stable. Blood pressure and blood oxygen
              values stayed near their recent ranges while sleep
              remained close to the daily target.
              {'\n\n'}
              This preview uses sample frontend data. The final
              clinical summary will be generated by the VitalPilot
              Notification and Reporting backend.
            </Text>
          ) : (
            <Text style={styles.body}>
              Generate a report preview to display a summary of
              your selected health period.
            </Text>
          )}
        </VitalCard>

        {message ? (
          <Text style={styles.message}>
            {message}
          </Text>
        ) : null}

        <VitalButton
          onPress={generateReportPreview}
        >
          Generate Report Preview
        </VitalButton>

        <VitalButton
          variant="secondary"
          onPress={downloadPdf}
        >
          Download PDF
        </VitalButton>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7FBF9',
  },

  content: {
    padding: 20,
    paddingBottom: BottomTabInset + 32,
    gap: 14,
  },

  title: {
    color: VitalPilotColors.title,
    fontSize: 28,
    fontWeight: '800',
  },

  subtitle: {
    color: '#667085',
    fontSize: 16,
    lineHeight: 24,
  },

  periodRow: {
    flexDirection: 'row',
    gap: 8,
  },

  period: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: VitalPilotColors.border,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },

  periodSelected: {
    backgroundColor:
      VitalPilotColors.mintStrong,
    borderColor:
      VitalPilotColors.primary,
  },

  periodText: {
    color: '#667085',
    fontWeight: '700',
  },

  periodTextSelected: {
    color:
      VitalPilotColors.primaryDark,
  },

  cardTitle: {
    color: VitalPilotColors.title,
    fontSize: 18,
    fontWeight: '800',
  },

  metricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },

  metricLabel: {
    color: '#667085',
  },

  metricValue: {
    color: VitalPilotColors.title,
    fontWeight: '700',
  },

  body: {
    color: '#667085',
    lineHeight: 22,
  },

  message: {
    color: '#667085',
    fontSize: 14,
    textAlign: 'center',
  },

  pressed: {
    opacity: 0.8,
  },
});